# Generated by Django 5.0 on 2023-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("contact", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.CharField(blank=True, max_length=150, null=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "logo_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="app/img/company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("otp", models.IntegerField()),
                ("role", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_created", models.DateTimeField(auto_now_add=True)),
                ("is_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobname", models.CharField(max_length=250)),
                ("companyname", models.CharField(max_length=250)),
                ("companyaddress", models.CharField(max_length=250)),
                ("jobdescription", models.TextField(max_length=500)),
                ("qualification", models.CharField(max_length=250)),
                ("responsibilities", models.CharField(max_length=250)),
                ("location", models.CharField(max_length=250)),
                ("companywebsite", models.CharField(max_length=250)),
                ("companyemail", models.CharField(max_length=250)),
                ("companycontact", models.CharField(max_length=20)),
                ("salarypackage", models.CharField(max_length=250)),
                ("experience", models.IntegerField()),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.usermaster"
            ),
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("contact", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("dob", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("min_salary", models.BigIntegerField(blank=True, null=True)),
                ("max_salary", models.BigIntegerField(blank=True, null=True)),
                ("job_type", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "jobcategory",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("highestedu", models.CharField(blank=True, max_length=150, null=True)),
                ("experience", models.CharField(blank=True, max_length=150, null=True)),
                ("website", models.CharField(blank=True, max_length=150, null=True)),
                ("shift", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "jobdescription",
                    models.CharField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="app/img/candidate"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.usermaster"
                    ),
                ),
            ],
        ),
    ]
