from django.db import models

# Create your models here.
class UserMaster(models.Model):
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=50)
    otp = models.IntegerField()
    role = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    is_created = models.DateTimeField(auto_now_add=True)
    is_updated = models.DateTimeField(auto_now_add=True)

class Candidate(models.Model):
    user_id = models.ForeignKey(UserMaster, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    contact = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    dob = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=50, null=True, blank=True)
    min_salary = models.BigIntegerField( null=True, blank=True)
    max_salary = models.BigIntegerField(null=True, blank=True)
    job_type = models.CharField(max_length=150, null=True, blank=True)
    jobcategory = models.CharField(max_length=150, null=True, blank=True)
    highestedu= models.CharField(max_length=150, null=True, blank=True)
    experience= models.CharField(max_length=150, null=True, blank=True)
    website = models.CharField(max_length=150, null=True, blank=True)
    shift = models.CharField(max_length=50, null=True, blank=True)
    jobdescription = models.CharField(max_length=500, default="", null=True, blank=True)
    profile_pic = models.ImageField(upload_to="app/img/candidate", null=True, blank=True)
    
class Company(models.Model):
    user_id = models.ForeignKey(UserMaster, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    company_name = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    contact = models.CharField(max_length=50, null=True, blank=True)
    website= models.CharField(max_length=150, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    logo_pic = models.ImageField(upload_to="app/img/company", null=True, blank=True)

class JobDetails(models.Model):
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    jobname = models.CharField(max_length=250)
    companyname = models.CharField(max_length=250)
    companyaddress = models.CharField(max_length=250)
    jobdescription = models.TextField(max_length=500)
    qualification = models.CharField(max_length=250)
    responsibilities= models.CharField(max_length=250)
    location= models.CharField(max_length=250)
    companywebsite= models.CharField(max_length=250)
    companyemail= models.CharField(max_length=250)
    companycontact= models.CharField(max_length=20)
    salarypackage= models.CharField(max_length=250)
    experience =models.IntegerField()